version: "3"

services:

  postgres:
    image: postgres:11
    container_name: mostly-tracker-db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mostlytracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    networks:
      - mostly-tracker

  tracker:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tracker
    ports:
      - 8080:8080
    network_mode: mostly-tracker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mostlytracker
      - SPRING_DATASOURCE_USERNAME=tracker
      - SPRING_DATASOURCE_PASSWORD=tracker
    depends_on:
      - postgres

networks:
  mostly-tracker: