version: "3"

services:

  time-tracker-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: time-tracker-app
    ports:
      - 8080:8080
    networks:
      - time-tracker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://time-tracker-db:5432/timetracker
      - SPRING_DATASOURCE_USERNAME=tracker
      - SPRING_DATASOURCE_PASSWORD=tracker
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:11
    container_name: time-tracker-db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timetracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    networks:
      - time-tracker
    restart: always

volumes:
  pgdata:

networks:
  time-tracker: